# Generated by Django 5.2.4 on 2025-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('variant', 'variant'), ('size', 'size')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductInteraction',
        ),
    ]
