# Generated by Django 5.2.4 on 2025-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('New', 'New'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
